name: EpicConsulting
favicon: null
layout_spectrum: 0.8847780881915241
typography_spectrum: 0.4081561863422394
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.045295146061107516
  lightness: 0.6564909564331174
  saturation: 0.32669982430525124
  rhythmicContrast: 0.413455595029518
purpose: []
